<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WhereFrom.Core\WhereFrom.Core.csproj" />
    <InternalsVisibleTo Include="WhereFrom.Platform.Windows.Tests" />
  </ItemGroup>
</Project>
